services:
  redis:
    image: redis:7-alpine

    container_name: autohub-redis

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

  api:
    build:
      context: .
      dockerfile: AutoHub.API/Dockerfile

    container_name: autohub-api

    ports:
      - "5000:8080"
    
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
     
      ConnectionStrings__DefaultConnection: Host=${DB_HOST};Port=${DB_PORT};Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}

      Jwt__Secret: ${JWT_SECRET}

      Redis__ConnectionString: ${REDIS_CONNECTION}

      Hangfire__Username: ${HANGFIRE_USERNAME}
      Hangfire__Password: ${HANGFIRE_PASSWORD}

      Storage__Provider: ${STORAGE_PROVIDER}
      Storage__BucketName: ${STORAGE_BUCKET}
      Storage__Endpoint: ${STORAGE_ENDPOINT}
      Storage__AccessKey: ${STORAGE_ACCESS_KEY}
      Storage__SecretKey: ${STORAGE_SECRET_KEY}
      Storage__Region: ${STORAGE_REGION}
      Storage__UseSSL: ${STORAGE_USE_SSL}


    depends_on:
      - redis

volumes:
  redis-data: