name: Autohub-API Deployment

on:
  push:
    branches:
      - 'release/*'
  
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from Github Actions"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Check .NET Version
        run: dotnet --info

      - name: Verify Repository
        run: |
          pwd
          ls -la
      
      - name: Restore NuGet Packages
        run: dotnet restore AutoHub.slnx

      - name: Build Solution
        run: dotnet build AutoHub.slnx --configuration Release --no-restore

      - name: Check for Test Projects
        run: dotnet test AutoHub.slnx --configuration Release --no-build
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: BRANCH_NAME
          script: |
            set -e

            echo "Deploying branch: $BRANCH_NAME"

            cd ~/projects/AutoHub-API

            git fetch origin

            git checkout $BRANCH_NAME

            git pull origin $BRANCH_NAME

            docker compose -f docker-compose.prod.yml stop autohub-api

            docker compose -f docker-compose.prod.yml up -d --build api

            docker compose -f docker-compose.prod.yml up -d

            docker image prune -f

            docker builder prune -af

            echo "Deployment completed successfully!"

            echo "Waiting 30 seconds for the application to start..."
            
            sleep 30

            echo "Starting health checks..."

            for i in {1..10}; do
              if curl -fs https://${{ secrets.DOMAIN }}/health > /dev/null; then
                echo "Application is healthy!"
                exit 0
              fi

              echo "Health check failed (Attempt $i/10). Retrying in 30 seconds..."
              sleep 30
            done

            echo "Health check failed after 10 attempts."
            exit 1